services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      API_BASE_URL: http://backend:8080/api/v1
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app/frontend
          ignore:
            - .venv/

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DB_LINK: postgresql://musicnotesdb_owner:auLZlMPhc28B@ep-square-heart-a4vyu584.us-east-1.aws.neon.tech/musicnotesdb?sslmode=require
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app/backend
          ignore:
            - .venv/
